### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by jgarte** [bufferswap/ViralityEngine#33]
A set of milestones to reach our first public release

# v0.3.0
- [ ] New Flow System
- [ ] New Graph Language
- [ ] Website with Documentation

# v0.4.0
- [ ] Extension System
- [x] Signed-distance Text Rendering
- [x] Dynamic Geometry
- [ ] Documentation up to date

# v0.5.0
- [ ] Model Abstraction Layer
- [ ] Interactive Prefabs
- [ ] Documentation up to date

# v0.6.0
- [ ] Draw Order
- [ ] OpenGL state changes encoded in materials and render component
- [ ] Multiple Render Passes
- [ ] Documentation up to date

# v0.7.0
- [ ] More collider shapes
- [ ] Collider sweep testing
- [ ] Spatial partitioning
- [ ] Documentation up to date

# v0.8.0
- [ ] Spatial audio support
- [ ] Finish texture types
- [ ] Documentation up to date

# v1.0.0 Public Beta
- [ ] Deployment capabilities
- [ ] Project skeleton generation
- [ ] Integration of extensions into project skeleton and deployment
- [ ] Documentation up to date

**Comment by jgarte** [comment]
@psilord Can the "Project skeleton generation" be checked off from the `v1.0.0` public beta task list?
